In [ ]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np

# =========================
# 프로젝트 경로 설정
# =========================

PROJECT_ROOT = Path("../..").resolve()
sys.path.append(str(PROJECT_ROOT / "src"))

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
PREPROCESSED_DIR = DATA_DIR / "preprocessed"
OUTPUT_DIR = DATA_DIR / "output"


print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_DIR:", DATA_DIR)
print("PREPROCESSED_DIR:", PREPROCESSED_DIR)


# src
from src.utils import read_csv_auto, check_dong_row_count

PROJECT_ROOT: /Users/masterj/Documents/GitHub/golmok-sesac_project
DATA_DIR: /Users/masterj/Documents/GitHub/golmok-sesac_project/data
PREPROCESSED_DIR: /Users/masterj/Documents/GitHub/golmok-sesac_project/data/preprocessed

In [2]:
# =========================
# CSV 파일 불러오기
# =========================

csv_files = list(PREPROCESSED_DIR.glob("*.csv"))

print(f"CSV 파일 개수: {len(csv_files)}")

for file in csv_files:
    print(file.name)

CSV 파일 개수: 10
cluster_df_yubeen.csv
merged_datamart.csv
merged_사업체.csv
merged_상권.csv
merged_인구.csv
merged_지하철.csv
동별 사업체수 현황.csv
서울시_마포구_동별_등록인구_전처리_최종.csv
서울시_상권분석_점포_입점_폐점율.csv
지하철 호선별 역별 승하차 인원 정보_2505~2605.csv

### merged_지하철과 merged_사업체 결합

In [3]:
subway_path = PREPROCESSED_DIR / "merged_지하철.csv"
biz_path = PREPROCESSED_DIR / "merged_사업체.csv"

df_subway = read_csv_auto(subway_path)
df_biz = read_csv_auto(biz_path)

로드 성공: merged_지하철.csv / encoding=utf-8-sig / shape=(11, 4)
로드 성공: merged_사업체.csv / encoding=utf-8-sig / shape=(16, 43)

In [4]:
df_merged = pd.merge(
    df_biz,
    df_subway,
    on="dong_nm",
    how="left"
)


print(df_merged.shape)
print(df_merged.columns)
df_merged.head()

(16, 46)
Index(['dong_nm', 'biz_cnt', 'emp_cnt', 'emp_male', 'emp_female',
       'a_agri_forestry_fishing_biz', 'a_agri_forestry_fishing_emp',
       'b_mining_biz', 'b_mining_emp', 'c_manufacturing_biz',
       'c_manufacturing_emp', 'd_electricity_gas_biz', 'd_electricity_gas_emp',
       'e_water_waste_biz', 'e_water_waste_emp', 'f_construction_biz',
       'f_construction_emp', 'g_wholesale_retail_biz',
       'g_wholesale_retail_emp', 'h_transport_storage_biz',
       'h_transport_storage_emp', 'i_accommodation_food_biz',
       'i_accommodation_food_emp', 'j_info_comm_biz', 'j_info_comm_emp',
       'k_finance_insurance_biz', 'k_finance_insurance_emp',
       'l_real_estate_biz', 'l_real_estate_emp', 'm_professional_sci_tech_biz',
       'm_professional_sci_tech_emp', 'n_business_support_biz',
       'n_business_support_emp', 'o_public_admin_biz', 'o_public_admin_emp',
       'p_education_biz', 'p_education_emp', 'q_health_social_biz',
       'q_health_social_emp', 'r_arts_sports_biz', 'r_arts_sports_emp',
       's_membership_repair_personal_biz', 's_membership_repair_personal_emp',
       'subway_line_count', 'subway_station_count', 'subway_total_psngr_co'],
      dtype='str')

,dong_nm,biz_cnt,emp_cnt,emp_male,emp_female,a_agri_forestry_fishing_biz,a_agri_forestry_fishing_emp,b_mining_biz,b_mining_emp,c_manufacturing_biz,...,p_education_emp,q_health_social_biz,q_health_social_emp,r_arts_sports_biz,r_arts_sports_emp,s_membership_repair_personal_biz,s_membership_repair_personal_emp,subway_line_count,subway_station_count,subway_total_psngr_co
0,공덕동,2412,12769,6587,6182,1,1,0,0,79,...,684,124,1101,52,149,212,510,4.0,1.0,30786905.0
1,아현동,3593,20416,11616,8800,0,0,0,0,290,...,470,113,1283,63,140,265,795,2.0,2.0,13224722.0
2,도화동,2897,21761,11610,10151,2,4,0,0,48,...,601,107,995,70,148,211,670,1.0,1.0,11063826.0
3,용강동,3729,19150,10498,8652,0,0,0,0,63,...,841,82,983,92,218,233,724,NaN,NaN,NaN
4,대흥동,1988,9699,4577,5122,0,0,0,0,51,...,3466,101,912,59,288,182,559,3.0,3.0,39710907.0

In [5]:
save_path = PREPROCESSED_DIR / "merged_datamart.csv"

df_merged.to_csv(save_path, index=False, encoding="utf-8-sig")

save_path

WindowsPath('C:/Users/user/Documents/GitHub/golmok-sesac_project/data/preprocessed/merged_datamart.csv')

### merged_datamart와 merged_인구 결합

In [6]:
datamart_path = PREPROCESSED_DIR / "merged_datamart.csv"
pop_path = PREPROCESSED_DIR / "merged_인구.csv"

df_datamart = read_csv_auto(datamart_path)
df_pop = read_csv_auto(pop_path)

df_merged = pd.merge(
    df_datamart,
    df_pop,
    on="dong_nm",
    how="left"
)

df_merged["subway_line_count"] = df_merged["subway_line_count"].fillna(0)
df_merged["subway_station_count"] = df_merged["subway_station_count"].fillna(0)
df_merged["subway_total_psngr_co"] = df_merged["subway_total_psngr_co"].fillna(0)

print(df_merged.shape)
print(df_merged.columns)
df_merged.head()

로드 성공: merged_datamart.csv / encoding=utf-8-sig / shape=(16, 46)
로드 성공: merged_인구.csv / encoding=utf-8-sig / shape=(16, 9)
(16, 54)
Index(['dong_nm', 'biz_cnt', 'emp_cnt', 'emp_male', 'emp_female',
       'a_agri_forestry_fishing_biz', 'a_agri_forestry_fishing_emp',
       'b_mining_biz', 'b_mining_emp', 'c_manufacturing_biz',
       'c_manufacturing_emp', 'd_electricity_gas_biz', 'd_electricity_gas_emp',
       'e_water_waste_biz', 'e_water_waste_emp', 'f_construction_biz',
       'f_construction_emp', 'g_wholesale_retail_biz',
       'g_wholesale_retail_emp', 'h_transport_storage_biz',
       'h_transport_storage_emp', 'i_accommodation_food_biz',
       'i_accommodation_food_emp', 'j_info_comm_biz', 'j_info_comm_emp',
       'k_finance_insurance_biz', 'k_finance_insurance_emp',
       'l_real_estate_biz', 'l_real_estate_emp', 'm_professional_sci_tech_biz',
       'm_professional_sci_tech_emp', 'n_business_support_biz',
       'n_business_support_emp', 'o_public_admin_biz', 'o_public_admin_emp',
       'p_education_biz', 'p_education_emp', 'q_health_social_biz',
       'q_health_social_emp', 'r_arts_sports_biz', 'r_arts_sports_emp',
       's_membership_repair_personal_biz', 's_membership_repair_personal_emp',
       'subway_line_count', 'subway_station_count', 'subway_total_psngr_co',
       'tot_pop', 'pop_00s', 'pop_10s', 'pop_20s', 'pop_30s', 'pop_40s',
       'pop_50s', 'pop_60s_above'],
      dtype='str')

,dong_nm,biz_cnt,emp_cnt,emp_male,emp_female,a_agri_forestry_fishing_biz,a_agri_forestry_fishing_emp,b_mining_biz,b_mining_emp,c_manufacturing_biz,...,subway_station_count,subway_total_psngr_co,tot_pop,pop_00s,pop_10s,pop_20s,pop_30s,pop_40s,pop_50s,pop_60s_above
0,공덕동,2412,12769,6587,6182,1,1,0,0,79,...,1.0,30786905.0,36648,1710,2107,5308,6927,5047,5979,9570
1,아현동,3593,20416,11616,8800,0,0,0,0,290,...,2.0,13224722.0,29566,2784,2319,2959,5940,5408,4281,5875
2,도화동,2897,21761,11610,10151,2,4,0,0,48,...,1.0,11063826.0,20486,1153,1408,2404,3712,2854,3216,5739
3,용강동,3729,19150,10498,8652,0,0,0,0,63,...,0.0,0.0,21497,1725,2239,1964,3453,4191,3312,4613
4,대흥동,1988,9699,4577,5122,0,0,0,0,51,...,3.0,39710907.0,16221,500,1034,4855,2774,1913,2178,2967

In [7]:
save_path = PREPROCESSED_DIR / "merged_datamart.csv"

df_merged.to_csv(save_path, index=False, encoding="utf-8-sig")

save_path

WindowsPath('C:/Users/user/Documents/GitHub/golmok-sesac_project/data/preprocessed/merged_datamart.csv')

### merged_datamart와 merged_상권 결합

In [8]:
datamart_path = PREPROCESSED_DIR / "merged_datamart.csv"
store_path = PREPROCESSED_DIR / "merged_상권.csv"

df_datamart = read_csv_auto(datamart_path)
df_store = read_csv_auto(store_path)

로드 성공: merged_datamart.csv / encoding=utf-8-sig / shape=(16, 54)
로드 성공: merged_상권.csv / encoding=utf-8-sig / shape=(16, 17)

In [9]:
# =========================
# 1. 병합 전 기본 확인
# =========================

print("df_datamart shape:", df_datamart.shape)
print("df_store shape:", df_store.shape)

print("\n[df_datamart dong_nm 개수]")
print(df_datamart["dong_nm"].nunique())

print("\n[df_store dong_nm 개수]")
print(df_store["dong_nm"].nunique())


# =========================
# 2. dong_nm 정리
# =========================
# 공백 때문에 매칭 안 되는 경우 방지

df_datamart["dong_nm"] = df_datamart["dong_nm"].astype(str).str.strip()
df_store["dong_nm"] = df_store["dong_nm"].astype(str).str.strip()


# =========================
# 3. 병합 전 동 목록 비교
# =========================

datamart_dongs = set(df_datamart["dong_nm"].unique())
store_dongs = set(df_store["dong_nm"].unique())

only_datamart = sorted(datamart_dongs - store_dongs)
only_store = sorted(store_dongs - datamart_dongs)
common_dongs = sorted(datamart_dongs & store_dongs)

print("\n[datamart에만 있는 동]")
print(only_datamart)

print("\n[store에만 있는 동]")
print(only_store)

print("\n[공통 동 개수]")
print(len(common_dongs))


# =========================
# 4. store 쪽 dong_nm 중복 확인
# =========================
# df_store는 dong_nm 기준으로 1행이어야 안전함.
# 중복이면 merge 후 행이 늘어남.

store_dup = (
    df_store["dong_nm"]
    .value_counts()
    .reset_index()
)

store_dup.columns = ["dong_nm", "count"]
store_dup = store_dup[store_dup["count"] > 1]

print("\n[df_store dong_nm 중복]")
display(store_dup)

if len(store_dup) > 0:
    print("주의: df_store에 dong_nm 중복이 있어서 merge 후 행 수가 늘어날 수 있습니다.")


# =========================
# 5. indicator로 병합 상태 확인
# =========================

df_merged_check = pd.merge(
    df_datamart,
    df_store,
    on="dong_nm",
    how="left",
    indicator=True
)

print("\n[merge 결과 shape]")
print(df_merged_check.shape)

print("\n[merge 상태]")
print(df_merged_check["_merge"].value_counts())


# =========================
# 6. 매칭 실패한 행 확인
# =========================

unmatched_rows = df_merged_check[
    df_merged_check["_merge"] == "left_only"
].copy()

print("\n[매칭 실패 행 수]")
print(len(unmatched_rows))

print("\n[매칭 실패 dong_nm]")
print(sorted(unmatched_rows["dong_nm"].unique()))

display(unmatched_rows.head())


# =========================
# 7. 병합하면서 새로 붙은 컬럼 결측 확인
# =========================

store_cols = [
    col for col in df_store.columns
    if col != "dong_nm"
]

missing_after_merge = (
    df_merged_check[store_cols]
    .isna()
    .sum()
    .reset_index()
)

missing_after_merge.columns = ["column", "missing_count"]
missing_after_merge["missing_ratio"] = (
    missing_after_merge["missing_count"] / len(df_merged_check)
)

missing_after_merge = missing_after_merge.sort_values(
    "missing_count",
    ascending=False
)

print("\n[store에서 붙은 컬럼의 결측 현황]")
display(missing_after_merge)


# =========================
# 8. 최종 병합본 생성
# =========================

df_merged = df_merged_check.drop(columns=["_merge"])

print("\n[최종 df_merged shape]")
print(df_merged.shape)

display(df_merged.head())

df_datamart shape: (16, 54)
df_store shape: (16, 17)

[df_datamart dong_nm 개수]
16

[df_store dong_nm 개수]
16

[datamart에만 있는 동]
[]

[store에만 있는 동]
[]

[공통 동 개수]
16

[df_store dong_nm 중복]

Empty DataFrame
Columns: [dong_nm, count]
Index: []

[merge 결과 shape]
(16, 71)

[merge 상태]
_merge
both          16
left_only      0
right_only     0
Name: count, dtype: int64

[매칭 실패 행 수]
0

[매칭 실패 dong_nm]
[]

Empty DataFrame
Columns: [dong_nm, biz_cnt, emp_cnt, emp_male, emp_female, a_agri_forestry_fishing_biz, a_agri_forestry_fishing_emp, b_mining_biz, b_mining_emp, c_manufacturing_biz, c_manufacturing_emp, d_electricity_gas_biz, d_electricity_gas_emp, e_water_waste_biz, e_water_waste_emp, f_construction_biz, f_construction_emp, g_wholesale_retail_biz, g_wholesale_retail_emp, h_transport_storage_biz, h_transport_storage_emp, i_accommodation_food_biz, i_accommodation_food_emp, j_info_comm_biz, j_info_comm_emp, k_finance_insurance_biz, k_finance_insurance_emp, l_real_estate_biz, l_real_estate_emp, m_professional_sci_tech_biz, m_professional_sci_tech_emp, n_business_support_biz, n_business_support_emp, o_public_admin_biz, o_public_admin_emp, p_education_biz, p_education_emp, q_health_social_biz, q_health_social_emp, r_arts_sports_biz, r_arts_sports_emp, s_membership_repair_personal_biz, s_membership_repair_personal_emp, subway_line_count, subway_station_count, subway_total_psngr_co, tot_pop, pop_00s, pop_10s, pop_20s, pop_30s, pop_40s, pop_50s, pop_60s_above, commercial_area_count, store_count, similar_store_count, franchise_store_count, open_store_count, close_store_count, net_open_store_count, similar_store_ratio, franchise_ratio, open_store_ratio, close_store_ratio, net_open_store_ratio, store_turnover_ratio, avg_open_rate, avg_close_rate, avg_turnover_rate, _merge]
Index: []

[0 rows x 71 columns]

[store에서 붙은 컬럼의 결측 현황]

                   column  missing_count  missing_ratio
0   commercial_area_count              0            0.0
1             store_count              0            0.0
2     similar_store_count              0            0.0
3   franchise_store_count              0            0.0
4        open_store_count              0            0.0
5       close_store_count              0            0.0
6    net_open_store_count              0            0.0
7     similar_store_ratio              0            0.0
8         franchise_ratio              0            0.0
9        open_store_ratio              0            0.0
10      close_store_ratio              0            0.0
11   net_open_store_ratio              0            0.0
12   store_turnover_ratio              0            0.0
13          avg_open_rate              0            0.0
14         avg_close_rate              0            0.0
15      avg_turnover_rate              0            0.0

[최종 df_merged shape]
(16, 70)

,dong_nm,biz_cnt,emp_cnt,emp_male,emp_female,a_agri_forestry_fishing_biz,a_agri_forestry_fishing_emp,b_mining_biz,b_mining_emp,c_manufacturing_biz,...,net_open_store_count,similar_store_ratio,franchise_ratio,open_store_ratio,close_store_ratio,net_open_store_ratio,store_turnover_ratio,avg_open_rate,avg_close_rate,avg_turnover_rate
0,공덕동,2412,12769,6587,6182,1,1,0,0,79,...,-8,1.071111,0.071111,0.014444,0.023333,-0.008889,0.037778,1.688827,1.490847,3.179674
1,아현동,3593,20416,11616,8800,0,0,0,0,290,...,-9,1.092754,0.092754,0.008696,0.034783,-0.026087,0.043478,1.579108,5.058333,6.637442
2,도화동,2897,21761,11610,10151,2,4,0,0,48,...,-7,1.125850,0.125850,0.018367,0.023129,-0.004762,0.041497,1.561374,2.515347,4.076722
3,용강동,3729,19150,10498,8652,0,0,0,0,63,...,-13,1.093750,0.093750,0.022059,0.034007,-0.011949,0.056066,1.463381,3.754537,5.217917
4,대흥동,1988,9699,4577,5122,0,0,0,0,51,...,-4,1.069034,0.069034,0.033531,0.041420,-0.007890,0.074951,3.080978,2.589815,5.670793

In [10]:
save_path = PREPROCESSED_DIR / "merged_datamart.csv"

df_merged.to_csv(save_path, index=False, encoding="utf-8-sig")

save_path

WindowsPath('C:/Users/user/Documents/GitHub/golmok-sesac_project/data/preprocessed/merged_datamart.csv')

In [14]:
print(df_merged.shape)

(16, 70)